workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'branches'

image: python:3.8


stages:
  - test


before_script:
    - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - cd src/
    - uvicorn main:app
    - APP_PID=$!  
    - sleep 5  
    - curl http://127.0.0.1:8000/
    - kill -SIGINT $APP_PID 
    - wait $APP_PID  
    - pytest -v 

mypy:
  stage: test
  script:
    - mypy src/

isort: 
  stage: test
  script:
    - isort --check-only --profile black src/

black:
  stage: test
  script:
    - black --diff --check src/

flask8:
  stage: test
  script:
    - flake8 src/