workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.12


stages:
  - test


before_script:
    - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - gunicorn app:app
    - APP_PID=$!  
    - sleep 5  
    - curl http://127.0.0.1:8000/
    - kill -SIGINT $APP_PID 
    - wait $APP_PID  
    - pytest -v 

mypy:
  stage: test
  script:
    - mypy app.py
    - mypy schemas/
    - mypy database/database
    - mypy database/models

isort: 
  stage: test
  script:
    - isort --check-only --profile black app.py
    - isort --check-only --profile black schemas/
    - isort --check-only --profile black database/

black:
  stage: test
  script:
    - black --diff --check app.py
    - black --diff --check schemas/
    - black --diff --check database/database
    - black --diff --check database/models

flask8:
  stage: test
  script:
    - flake8 app.py
    - flake8 schemas/
    - flake8 database/models
    - flake8 database/database