version: '3.8'
services:
  app:
    container_name: tweet_app
    build: .
    ports:
      - "8000:5050"
    networks:
      - mynetwork
    environment:
      - DB_LOGIN=${DB_LOGIN}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db_log:/var/lib/postgresql/pg_log
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

