services:
  app:
    container_name: tweet_app
    build: .
    ports:
      - "8000:5050"
    networks:
      - mynetwork
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db_log:/var/lib/postgresql/pg_log
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

secrets:
  db_user:
    external: true
  db_password:
    external: true