services:
  app:
    container_name: tweet_app
    build: .
    ports:
      - "8000:5050"
    networks:
      - mynetwork
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=tweet_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db_log:/var/lib/postgresql/pg_log
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
